[build]
  command = "bun run build"
  publish = "dist"

[dev]
  command = "bun run dev"
  port = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"